import { test, expect } from '@playwright/test';

test.describe.configure({ mode: "serial" }); // Jika ingin test berurutan (opsional)
test.describe("Kesiswaan - Absensi", () => {

// Gunakan state login dari guru
test.use({ storageState: 'guruState.json' });

test('Absensi per Pelajaran', async ({ page }) => {
   await page.goto('https://esbeta.deanry.my.id/dashboard');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('hacked');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList').getByText('Jl. Teluk Pacitan, Arjosari,').click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.getByRole('link', { name: ' Kesiswaan ' }).click();
  await page.getByRole('link', { name: ' Absensi ' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Absensi per Pelajaran' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('link', { name: ' Kurikulum ' }).click();
  await page1.getByRole('link', { name: ' Jadwal Pelajaran' }).click();
  await page1.getByRole('link', { name: ' Kesiswaan ' }).click();
  await page1.getByRole('link', { name: ' Absensi ' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('link', { name: 'Absensi per Pelajaran' }).click();
  const page2 = await page2Promise;
  await page2.getByRole('button', { name: ' Absensi' }).click();
  await page2.locator('#timetable_class_section').selectOption('12');
  await page2.getByLabel('Jadwal').selectOption('2206');
  await page2.getByRole('textbox', { name: 'Tgl', exact: true }).click();
  await page2.getByRole('textbox', { name: 'Materi' }).click();
  await page2.getByRole('textbox', { name: 'Materi' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Materi' }).fill('S');
  await page2.getByRole('textbox', { name: 'Materi' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Materi' }).fill('Silat');
  await page2.getByText('lampiran').click();
  await page2.getByRole('dialog', { name: 'Tambah Absensi' }).setInputFiles('Teknik pukulan depan.pdf');
  await page2.getByRole('button', { name: 'Hadir Semua' }).click();
  await page2.getByRole('row', { name: '29 20247797 29 SRIASIH INDAH' }).locator('label').nth(1).click();
  await page2.getByRole('row', { name: '23 20247791 23 RISKI EKA' }).getByLabel('Izin').check();
  await page2.getByRole('row', { name: '15 20247783 15 MOHAMMAD REVA' }).locator('div').nth(3).click();
  await page2.getByRole('button', { name: 'Simpan' }).click();
  await page2.getByRole('button', { name: 'Refresh' }).click();
  await page2.getByRole('button', { name: 'Columns' }).click();
  await page2.getByRole('checkbox', { name: 'Jam Mulai' }).check();
  await page2.getByRole('checkbox', { name: 'Jam Selesai' }).check();
  await page2.locator('label').filter({ hasText: 'Jam Mulai' }).click();
  await page2.locator('label').filter({ hasText: 'Jam Selesai' }).click();
  await page2.getByRole('searchbox', { name: 'Search' }).click();
  await page2.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page2.getByRole('searchbox', { name: 'Search' }).fill('');
  await page2.getByRole('row', { name: '1 MULOK PJOK XII TKJ C 17-06-' }).getByRole('link').click();
  await page2.goto('http://esbeta.deanry.my.id/subject-attendance');
  const page3Promise = page2.waitForEvent('popup');
  await page2.getByRole('link', { name: ' Lampiran' }).click();
  const page3 = await page3Promise;
  await page2.getByRole('row', { name: '1 2024/20257836 1 ALIF' }).locator('#ngedit').click();
  await page2.getByLabel('Edit Kehadiran Siswa Nama Siswa Total jam pelajaran Status Kehadiran Hadir Sakit Izin Alpa Tutup Simpan', { exact: true }).getByText('Sakit').click();
  page2.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page2.getByRole('button', { name: 'Simpan' }).click();
  await page2.goto('http://esbeta.deanry.my.id/subject-attendance');
  await page2.getByRole('link', { name: ' Jadwal Pelajaran' }).click();
  await page2.getByRole('link', { name: ' Absensi ' }).click();
  const page4Promise = page2.waitForEvent('popup');
  await page2.getByRole('link', { name: 'Absensi per Pelajaran' }).click();
  const page4 = await page4Promise;
  await page4.getByRole('row', { name: '1 MULOK PJOK XII TKJ C 17-06-' }).getByRole('link').click();
  await page4.getByRole('dialog', { name: ' Absensi Pelajaran MULOK' }).click();
  await page4.getByRole('button', { name: 'Close' }).click();
  const page5Promise = page4.waitForEvent('popup');
  await page4.getByRole('link', { name: 'Absensi Kegiatan Khusus', exact: true }).click();
  const page5 = await page5Promise;
  const page6Promise = page5.waitForEvent('popup');
  await page5.getByRole('link', { name: 'Absensi per Pelajaran' }).click();
  const page6 = await page6Promise;
  await page5.getByRole('link', { name: ' Jadwal Pelajaran' }).click();
  await page5.getByRole('link', { name: ' Absensi ' }).click();
  const page7Promise = page5.waitForEvent('popup');
  await page5.getByRole('link', { name: 'Absensi per Pelajaran' }).click();
  const page7 = await page7Promise;
  await page7.getByRole('row', { name: '3 MULOK PJOK XI TKJ A 17-06-' }).getByRole('link').click();
  await page7.goto('http://esbeta.deanry.my.id/subject-attendance');
  await page7.getByRole('dialog', { name: ' Absensi Pelajaran MULOK' }).click();
  await page7.getByRole('button', { name: 'Close' }).click();
  await page7.getByRole('link', { name: ' Jadwal Pelajaran' }).click();
  await page7.getByRole('link', { name: ' Absensi ' }).click();
  const page8Promise = page7.waitForEvent('popup');
  await page7.getByRole('link', { name: 'Absensi per Pelajaran' }).click();
  const page8 = await page8Promise;
  await page8.getByRole('row', { name: '2 MULOK PJOK XII RPL B 17-06-' }).getByRole('link').click();
  await page8.getByRole('row', { name: '20247181 1 ADIATMA WAHYUDI  hadir ' }).locator('#ngedit').click();
  await page8.getByLabel('Edit Kehadiran Siswa Nama Siswa Total jam pelajaran Status Kehadiran Hadir Sakit Izin Alpa Tutup Simpan', { exact: true }).getByText('Sakit').click();
  page8.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('dialog', { name: ' Edit Kehadiran Siswa Close Nama Siswa ADIATMA WAHYUDI Total jam pelajaran Status Kehadiran Hadir Sakit Izin Alpa Tutup Simpan', exact: true }).getByLabel('Close').click();
  await page8.goto('https://esbeta.deanry.my.id/subject-attendance');
  await page8.getByRole('row', { name: '2 MULOK PJOK XII RPL B 17-06-' }).getByRole('link').click();
  await page8.goto('http://esbeta.deanry.my.id/subject-attendance');
  await page8.getByRole('button', { name: 'Close' }).click();
  const downloadPromise = page8.waitForEvent('download');
  await page8.getByRole('button', { name: '' }).click();
  const download = await downloadPromise;
  const download1Promise = page8.waitForEvent('download');
  await page8.getByRole('button', { name: '' }).click();
  const download1 = await download1Promise;
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.getByRole('button', { name: 'Tutup' }).click();
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.locator('#timetable_class_section').selectOption('12');
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.locator('#timetable_class_section').selectOption('13');
  await page8.locator('#timetable_class_section').selectOption('12');
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.getByLabel('Jadwal').selectOption('2206');
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.locator('#timetable_class_section').selectOption('16');
  await page8.getByRole('row', { name: '26 2024/202571200 26 NAFHISYA' }).getByRole('cell').nth(4).click();
  await page8.goto('https://esbeta.deanry.my.id/subject-attendance');
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.locator('#timetable_class_section').selectOption('16');
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.getByLabel('Jadwal').selectOption('2595');
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.getByRole('textbox', { name: 'Materi' }).click();
  await page8.getByRole('textbox', { name: 'Materi' }).fill('S');
  await page8.getByRole('textbox', { name: 'Materi' }).press('CapsLock');
  await page8.getByRole('textbox', { name: 'Materi' }).fill('Silat');
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.getByText('lampiran').click();
  await page8.getByRole('dialog', { name: 'Tambah Absensi' }).setInputFiles('Teknik pukulan depan.pdf');
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('button', { name: ' Absensi' }).click();
  await page8.getByText('lampiran').click();
  await page8.getByRole('dialog', { name: 'Tambah Absensi' }).setInputFiles('Teknik pukulan depan.pdf');
  await page8.getByRole('button', { name: 'Hadir Semua' }).click();
  await page8.getByRole('dialog', { name: 'Tambah Absensi' }).getByPlaceholder('Search').click();
  await page8.getByRole('dialog', { name: 'Tambah Absensi' }).getByPlaceholder('Search').fill('anjas');
  await page8.getByText('Hadir', { exact: true }).click();
  await page8.getByRole('dialog', { name: 'Tambah Absensi' }).getByPlaceholder('Search').click();
  await page8.getByRole('dialog', { name: 'Tambah Absensi' }).getByPlaceholder('Search').fill('');
  await page8.getByRole('button', { name: 'Hadir Semua' }).click();
  await page8.getByRole('button', { name: 'Simpan' }).click();
  await page8.getByRole('button', { name: 'Refresh' }).click();
});
});