import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://esbeta.deanry.my.id/dashboard');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.coms');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('mkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList div').filter({ hasText: 'SMKN 8 MALANG Jl. Teluk' }).first().click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.goto('http://esbeta.deanry.my.id/dashboard');
  await page.getByRole('link', { name: ' Sarpras ' }).click();
  await page.getByRole('link', { name: ' Dokumen Sarpras' }).click();
  await page.getByRole('link', { name: ' Sarpas' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/sarpasindex/2');
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.locator('.fixed-table-toolbar').click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'XML' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: ' PDSM ' }).click();
  await page.getByRole('link', { name: ' Dokumen PDSM' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).fill('L');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan G');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan Guru ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan Guru A');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan Guru Absen');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('R');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Rekap ');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Rekap G');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Rekap Guru ');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Rekap Guru A');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Rekap Guru Absen');
  await page.locator('#editFolderForm').getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('row', { name: '1 Rekap Guru Absen 30 Juni' }).locator('#deleteFolderForm').getByRole('button').click();
  await page.getByRole('button', { name: 'Hapus' }).click();
  await page.getByRole('link', { name: ' Data PKG' }).click();
  await page.getByRole('link', { name: 'Dokumen PDSM' }).click();
  await page.getByRole('link', { name: 'Dokumen PDSM', exact: true }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/pdsmfolder/create');
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('L');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan G');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan Guru ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan Guru T');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan Guru Tidak ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan Guru Tidak A');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Laporan Guru Tidak Absen');
  await page.getByRole('button', { name: 'Atur ulang' }).click();
  await page.getByRole('link', { name: 'Dokumen PDSM', exact: true }).click();
  await page.getByRole('link', { name: ' Data PKG' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('R');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Rekap ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Rekap PKG ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Rekap PKG B');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Rekap PKG Bulan ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Rekap PKG Bulan M');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Rekap PKG Bulan Maret');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('RE');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG B');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG Bulan ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG Bulan M');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG Bulan Maret');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/pdsmindex/2');
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen PDSM' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList').getByText('Jl. Teluk Pacitan, Arjosari,').click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.goto('http://esbeta.deanry.my.id/dashboard');
  await page.getByRole('link', { name: ' PDSM ' }).click();
  await page.getByRole('link', { name: ' Dokumen PDSM' }).click();
  await page.getByRole('link', { name: ' Data PKG' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG B');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan A');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan April');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan April');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan April');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('link', { name: 'Dokumen PDSM', exact: true }).click();
  await page.getByRole('link', { name: ' Data PKG' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG B');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan M');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan Mei');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar PKG B');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar PKG Bulan ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar PKG Bulan M');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar PKG Bulan Mei');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/pdsmindex/2');
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG B');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan J');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Daftar PKG Bulan Januari');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('R');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG B');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG Bulan ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG Bulan J');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rekap PKG Bulan Januari');
  await page.getByRole('button', { name: 'Atur' }).click();
  await page.getByRole('link', { name: 'Dokumen PDSM', exact: true }).click();
  await page.getByRole('link', { name: ' Data PKG' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('M');
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('A');
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByText('File Unggahan Pengenal No').click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'JSON' }).click();
  const download1 = await download1Promise;
  await page.getByRole('link', { name: ' TU ' }).click();
  await page.getByRole('link', { name: ' TU ' }).click();
  await page.getByRole('link', { name: ' TU ' }).click();
  await page.getByRole('link', { name: ' Cuti ' }).click();
  await page.getByRole('link', { name: 'Cuti', exact: true }).click();
  await page.getByRole('textbox', { name: 'Alasan' }).click();
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('S');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit ');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit D');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit Demam');
  await page.getByRole('textbox', { name: 'Dari Tanggal' }).click();
  await page.getByRole('cell', { name: '30' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Hingga Tanggal.' }).click();
  await page.getByRole('cell', { name: '30' }).nth(3).click();
  await page.getByRole('button', { name: 'Unggah' }).click();
  await page.getByRole('button', { name: 'Unggah' }).setInputFiles('surat izin2.png');
  await page.locator('label').filter({ hasText: 'Penuh' }).locator('i').click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('S');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit ');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit P');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit Pusing');
  await page.locator('#from_date').click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('cell', { name: '30', exact: true }).nth(1).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('cell', { name: '30', exact: true }).nth(1).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('.col-sm-12').first().click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Alasan' }).click();
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('S');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit ');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit Masuk angin');
  await page.locator('#from_date').click();
  await page.getByRole('cell', { name: '30', exact: true }).nth(1).click();
  await page.locator('#to_date').click();
  await page.getByRole('cell', { name: '30', exact: true }).nth(1).click();
  await page.getByRole('button', { name: 'Unggah' }).click();
  await page.getByRole('button', { name: 'Unggah' }).setInputFiles('Log-Book Magang_Zara Salsa Aulia.pdf');
  await page.getByText('Setengah hari pertama').click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Unggah' }).click();
  await page.getByRole('button', { name: 'Unggah' }).setInputFiles('Audio WhatsApp 2025-06-29 pukul 17.08.41_ae9f6850.dat (online-audio-converter.com).mp3');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('body').press('ControlOrMeta+r');
  await page.getByRole('textbox', { name: 'Alasan' }).click();
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('S');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit ');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Alasan' }).fill('Sakit Masuk angin');
  await page.getByRole('textbox', { name: 'Dari Tanggal' }).click();
  await page.getByRole('cell', { name: '30', exact: true }).nth(1).click();
  await page.getByRole('textbox', { name: 'Hingga Tanggal.' }).click();
  await page.getByRole('cell', { name: '30', exact: true }).nth(1).click();
  await page.getByRole('button', { name: 'Unggah' }).click();
  await page.getByRole('button', { name: 'Unggah' }).setInputFiles('Audio WhatsApp 2025-06-29 pukul 17.08.41_ae9f6850.dat (online-audio-converter.com).mp3');
  await page.getByText('Setengah hari pertama').click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('#session_year_id').selectOption('3');
  await page.locator('#session_year_id').selectOption('1');
  await page.locator('#filter_upcoming').selectOption('Today');
  await page.locator('#filter_upcoming').selectOption('Tomorrow');
  await page.locator('#filter_upcoming').selectOption('Upcoming');
  await page.locator('#filter_upcoming').selectOption('All');
  await page.locator('#filter_month_id').selectOption('5');
  await page.locator('#filter_month_id').selectOption('');
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('S');
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Lampiran' }).nth(1).click();
  await page.locator('.content-wrapper > div > div:nth-child(2)').click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.getByRole('checkbox', { name: 'Lampiran' }).check();
  await page.getByRole('button', { name: 'Export' }).click();
  const download2Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'SQL' }).click();
  const download2 = await download2Promise;
  await page.getByRole('row', { name: '1 30-06-2025 30-06-2025 Sakit' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Lihat' }).click();
  await page.getByRole('button', { name: 'Tutup' }).click();
  await page.getByRole('row', { name: '2 30-06-2025 30-06-2025 Sakit' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Lihat' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'surat izin2.png' }).click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'Tutup' }).click();
  await page.getByRole('row', { name: '2 30-06-2025 30-06-2025 Sakit' }).locator('#dropdownMenuButton').click();
  await page.getByRole('row', { name: '1 30-06-2025 30-06-2025 Sakit' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Hapus' }).click();
  await page.getByRole('button', { name: 'Ya, hapus' }).click();
  await page.getByRole('button', { name: '10' }).click();
  await page.getByRole('link', { name: '5' }).click();
  await page.getByRole('link', { name: 'next page' }).click();
  await page.getByRole('link', { name: 'to page 1' }).click();
  await page.getByRole('link', { name: 'next page' }).click();
  await page.getByRole('link', { name: 'previous page' }).click();
  await page.getByRole('link', { name: ' Dokumen TU' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('R');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Rapor kelas ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Rapor kelas X');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Rapor kelas X smt ');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Rapor kelas X smt Genap');
  await page.locator('#editFolderForm').getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('row', { name: '1 Rapor kelas X smt Genap 30' }).locator('#deleteFolderForm').getByRole('button').click();
  await page.getByRole('button', { name: 'Hapus' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/tufolder/create');
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('R');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Rapor');
  await page.getByRole('button', { name: 'Atur ulang' }).click();
  await page.getByRole('link', { name: 'Dokumen TU', exact: true }).click();
  await page.locator('div:nth-child(2) > .course-card > .card-body').click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('U');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan R');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan Rapat ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan Rapat S');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan Rapat Staf');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('undangan rapat.png');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('R');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rapat staf (');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('Shift+CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rapat staf (G');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rapat staf (Guru dan staf) ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Rapat staf (Guru dan staf) SMKN 8');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen TU' }).click();
  await page.getByRole('link', { name: ' SURAT UNDANGAN' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('U');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan rapat staf ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan rapat staf TU');
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('U');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan rapat staf ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan rapat staf TU');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ControlOrMeta+A');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ControlOrMeta+C');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ControlOrMeta+V');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('undangan rapat.png');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen TU' }).click();
  await page.getByRole('link', { name: ' SURAT UNDANGAN' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('U');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan rapat kepsek');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Log-Book Magang_Zara Salsa Aulia.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('U');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Undangan rapat guru');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Job Magang UBIG.mp4');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByText('Nama Tanggal File * Upload').click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('K');
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const download3Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'JSON' }).click();
  const download3 = await download3Promise;
  await page.getByRole('link', { name: ' Dokumen Perpus' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman B');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman Buku ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman Buku M');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman Buku bulan');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman Buku bulan M');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman Buku bulan Maret');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Peminjaman Buku bulan ');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Peminjaman Buku bulan J');
  await page.getByRole('textbox', { name: 'Nama Folder' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Peminjaman Buku bulan Januari');
  await page.locator('#editFolderForm').getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('row', { name: '1 Peminjaman Buku bulan' }).locator('#deleteFolderForm').getByRole('button').click();
  await page.getByRole('button', { name: 'Hapus' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/perpusfolder/create');
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).fill('p');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman buku bulan ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman buku bulan M');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Peminjaman buku bulan Mei');
  await page.getByRole('button', { name: 'Atur ulang' }).click();
  await page.getByRole('link', { name: 'Dokumen Perpus', exact: true }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/perpusfolder');
  await page.getByRole('link', { name: ' Peminjaman Buku' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku paket ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku paket IPS');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('peminjaman buku.png');
  await page.getByRole('button', { name: 'Upload File Upload File' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('P');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman B');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman Buku ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman Buku P');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman Buku Paket ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman Buku Paket IPS');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman Buku Paket IPS oleh kelas ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman Buku Paket IPS oleh kelas X RPL C');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen Perpus' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('');
  await page.getByRole('textbox', { name: 'Email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email Email harus diisi' }).fill('agungcahyono533@gmail.com');
  await page.locator('#frmLogin div').filter({ hasText: 'Password' }).first().click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByText('SMKN 8 MALANG Jl. Teluk').click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.getByRole('link', { name: ' Perpus ' }).click();
  await page.getByRole('link', { name: ' Dokumen Perpus' }).click();
  await page.getByRole('link', { name: ' Peminjaman Buku' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku paket fisika');
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjman buku paket fisika');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku paket fisika');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('peminjaman buku.png');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('P');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman buku paket fisika oleh kelas ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman buku paket fisika oleh kelas X M');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman buku paket fisika oleh kelas X Metro ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Peminjaman buku paket fisika oleh kelas X Metro A');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: ' TU ' }).click();
  await page.getByRole('link', { name: ' Dokumen TU' }).click();
  await page.getByRole('link', { name: ' SURAT UNDANGAN' }).click();
  await page.getByRole('row', { name: '1 Undangan rapat staf TU 30-' }).locator('#dropdownMenuButton').click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Lihat' }).click();
  const page2 = await page2Promise;
  await page.getByRole('row', { name: '1 Undangan rapat staf TU 30-' }).locator('#dropdownMenuButton').click();
  const download4Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Unduh' }).click();
  const download4 = await download4Promise;
  await page.getByRole('link', { name: ' Dokumen Perpus' }).click();
  await page.getByText('Peminjaman Buku 2').click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku paket ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku paket PAI');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Log-Book Magang_Zara Salsa Aulia.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Dipinjam oleh ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Dipinjam oleh X E');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Dipinjam oleh X Elin ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Dipinjam oleh X Elin B');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/perpusindex/6');
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku PAI');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Job Magang UBIG.mp4');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Peminjaman buku Pai');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('peminjaman buku.png');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Dipinjam oleh kelas ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Dipinjam oleh kelas X Rpl ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Dipinjam oleh kelas X Rpl A');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('button', { name: 'Atur' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('F');
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByText('Loading, please wait NoNama').click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.getByRole('checkbox', { name: 'Deskripsi' }).check();
  await page.getByRole('button', { name: 'Export' }).click();
  const download5Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'CSV' }).click();
  const download5 = await download5Promise;
  await page.getByRole('link', { name: ' KPK TKJ ' }).click();
  await page.getByRole('link', { name: ' Dokumen KPK TKJ' }).click();
  await page.getByRole('link', { name: ' TKJ' }).click();
  await page.getByRole('link', { name: ' KPK Metro ' }).click();
  await page.getByRole('link', { name: ' Dokumen KPK Metro' }).click();
  await page.getByText('Dokument Metro 0').click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Sertifikasi ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Sertifikasi F');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Sertifikasi Festo');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('festo.jpeg');
  await page.getByRole('button', { name: 'Upload File Upload File' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('S');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Sertifikasi untuk metroelin');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen KPK Metro' }).click();
  await page.getByRole('link', { name: ' Dokument Metro' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.goto('https://esbeta.deanry.my.id/folder/kpk_metroindex/3');
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).press('ControlOrMeta+R');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('l');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('L');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba R');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba Robotik');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('2025-06-30');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('festo.jpeg');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba robotik internasonal');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Log-Book Magang_Zara Salsa Aulia.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/kpk_metroindex/3');
  await page.getByRole('link', { name: 'Dokumen KPK Metro' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('amkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList').getByText('Jl. Teluk Pacitan, Arjosari,').click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.getByRole('link', { name: ' KPK Metro ' }).click();
  await page.getByRole('link', { name: ' Dokumen KPK Metro' }).click();
  await page.getByRole('link', { name: ' Dokument Metro' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('L');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba Robot ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba Robot Internasional');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Log-Book Magang_Zara Salsa Aulia.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba robotik internasional');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Job Magang UBIG.mp4');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('L');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba roboyk internasional');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Job Magang UBIG.mp4');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Lomba Nasional');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('festo.jpeg');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('lomba robotik nasional');
  await page.getByRole('button', { name: 'Atur' }).click();
  await page.locator('.fixed-table-toolbar').click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const download6Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'MS-Excel' }).click();
  const download6 = await download6Promise;
  await page.getByRole('row', { name: '1 Lomba Robotik 30-06-2025 30' }).locator('#dropdownMenuButton').click();
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Lihat' }).click();
  const page3 = await page3Promise;
  await page.getByRole('row', { name: '1 Lomba Robotik 30-06-2025 30' }).locator('#dropdownMenuButton').click();
  const download7Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Unduh' }).click();
  const download7 = await download7Promise;
  await page.getByRole('link', { name: ' KPK RPL ' }).click();
  await page.getByRole('link', { name: ' Dokumen KPK RPL' }).click();
  await page.getByRole('link', { name: ' UUK Ganjil' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Sertifikasi ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Sertifikasi Oracle');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('oracle.png');
  await page.getByRole('button', { name: 'Upload File Upload File' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Sertifikasi ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Sertifikasi Oracle 2025');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles([]);
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('oracle.png');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen KPK RPL' }).click();
  await page.getByRole('link', { name: ' UUK Ganjil' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama This field is required.' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama This field is required.' }).fill('M');
  await page.getByRole('textbox', { name: 'Nama This field is required.' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('2025-06-30');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('image (10).png');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen KPK RPL' }).click();
  await page.getByText('UUK Ganjil 2024 2').click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('M');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Materi ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Materi Dekstop');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Log-Book Magang_Zara Salsa Aulia.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/kpk_rplindex/2');
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('M');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Materi ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Materi Dekstop');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Job Magang UBIG.mp4');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('span').filter({ hasText: 'Deskripsi' }).click();
  await page.locator('span').filter({ hasText: 'Deskripsi' }).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const download8Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'CSV' }).click();
  const download8 = await download8Promise;
  await page.getByRole('link', { name: 'to page 2' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/kpk_rplindex/2');
  await page.getByRole('textbox', { name: 'Cari' }).click();
  await page.getByRole('textbox', { name: 'Cari' }).fill('eli');
  await page.getByRole('link', { name: ' KPK ELIN ' }).click();
  await page.getByRole('link', { name: ' Dokumen KPK ELIN' }).click();
  await page.getByRole('link', { name: ' UUK Gasal' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Sertifikasi ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Sertifikasi Festo');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('festo.jpeg');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Sertifikasi ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Sertifikasi Festo 2025');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen KPK Elin' }).click();
  await page.getByRole('link', { name: ' UUK Gasal' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('K');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Kisi-');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Kisi-Kisi ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('2025-06-30');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('administrasi.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen KPK Elin' }).click();
  await page.getByRole('link', { name: ' UUK Gasal' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Materi sertifikasi');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Log-Book Magang_Zara Salsa Aulia.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/kpk_elinindex/5');
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Materi sertifikasi');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Job Magang UBIG.mp4');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('ateri sertifikasi');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('materi sertifikasi');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('festo.jpeg');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('materi industri');
  await page.getByRole('button', { name: 'Atur' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.locator('.fixed-table-toolbar').click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('span').filter({ hasText: 'Deskripsi' }).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const download9Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'XML' }).click();
  const download9 = await download9Promise;
  await page.getByRole('row', { name: '1 Kisi-Kisi UKK 30-06-2025 30' }).locator('#dropdownMenuButton').click();
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Lihat' }).click();
  const page4 = await page4Promise;
  await page.getByRole('row', { name: '1 Kisi-Kisi UKK 30-06-2025 30' }).locator('#dropdownMenuButton').click();
  const download10Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Unduh' }).click();
  const download10 = await download10Promise;
  await page.getByRole('link', { name: ' KPK RPL ' }).click();
  await page.getByRole('link', { name: ' Dokumen KPK RPL' }).click();
  await page.getByRole('link', { name: ' UUK Ganjil' }).click();
  await page.getByRole('row', { name: '1 Materi web 30-06-2025 30-06' }).locator('#dropdownMenuButton').click();
  const page5Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Lihat' }).click();
  const page5 = await page5Promise;
  await page.getByRole('row', { name: '1 Materi web 30-06-2025 30-06' }).locator('#dropdownMenuButton').click();
  const download11Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Unduh' }).click();
  const download11 = await download11Promise;
});