import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://esbeta.deanry.my.id/');
  await page.getByRole('list').getByRole('link', { name: 'Beranda' }).click();
  await page.getByRole('list').getByRole('link', { name: 'Fitur' }).click();
  await page.getByRole('list').getByRole('link', { name: 'Tentang Kami' }).click();
  await page.getByRole('list').getByRole('link', { name: 'Harga' }).click();
  await page.getByText('Beranda Fitur Tentang Kami Harga Kontak Bahasa English Bahasa Indonesia Login').first().click();
  await page.getByRole('button', { name: 'Bahasa' }).click();
  await page.getByRole('link', { name: 'Bahasa Indonesia' }).click();
  await page.goto('https://esbeta.deanry.my.id/#about-us');
  await page.getByRole('button', { name: 'Daftarkan Sekolah Anda' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Lihat Fitur Lainnya' }).click();
  await page.getByRole('link', { name: 'Hubungi Kami' }).click();
  await page.getByRole('textbox', { name: 'Masukkan Nama Anda' }).click();
  
  await page.getByRole('textbox', { name: 'Masukkan Nama Anda' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Masukkan Nama Anda' }).fill('Anonim');
  await page.getByRole('textbox', { name: 'Masukkan Email Anda' }).click();
  await page.getByRole('textbox', { name: 'Masukkan Email Anda' }).fill('anonim123@gmail.com');
  await page.getByRole('textbox', { name: 'Kirim Pesan Anda' }).click();
  
  await page.getByRole('textbox', { name: 'Kirim Pesan Anda' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kirim Pesan Anda' }).fill('Semangat');
  await page.getByRole('button', { name: 'Kirim' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('.infoWrapper').first().click();
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  await page.getByText('eschoolac@gmail.com').click();
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  await page.getByText('Lokasi Ruko Modern Kav A16-').click();
  const page3 = await page3Promise;
  await page.getByRole('contentinfo').getByRole('link', { name: 'Beranda' }).click();
  await page.getByRole('contentinfo').getByRole('link', { name: 'Fitur' }).click();
  await page.getByRole('contentinfo').getByRole('link', { name: 'Harga' }).click();
  await page.getByRole('contentinfo').getByRole('link', { name: 'Harga' }).click();
  await page.getByRole('link', { name: 'FAQ' }).click();
  await page.getByRole('contentinfo').getByRole('link', { name: 'Tentang Kami' }).click();
  await page.getByRole('contentinfo').getByRole('link', { name: 'Kontak' }).click();
  await page.getByRole('link', { name: 'Kebijakan Privasi' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Start Trial' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Language' }).click();
  await page.getByRole('link', { name: 'Bahasa Indonesia' }).click();
  await page.getByRole('link', { name: 'Syarat & Ketentuan' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Beranda' }).click();
  await page.getByRole('list').getByRole('link', { name: 'Fitur' }).click();
  await page.getByRole('list').getByRole('link', { name: 'Tentang Kami' }).click();
  await page.getByRole('list').getByRole('link', { name: 'Harga' }).click();
  await page.getByRole('list').getByRole('link', { name: 'Kontak' }).click();
  await page.goto('https://esbeta.deanry.my.id/page/type/terms-conditions');
  await page.getByRole('link', { name: 'Pengembalian Dana' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Uji Coba' }).click();
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Facebook' }).click();
  const page4 = await page4Promise;
  const page5Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Instagram' }).click();
  const page5 = await page5Promise;
  const page6Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'LinkedIn' }).click();
  const page6 = await page6Promise;
});