import { test, expect } from '@playwright/test';

test.describe.configure({ mode: "serial" }); // Jika ingin test berurutan (opsional)
test.describe("Tes Dokumen Humas", () => {

// Gunakan state login dari guru
test.use({ storageState: 'guruState.json' });

test('Dkumen Humas', async ({ page }) => {
  await page.goto('https://esbeta.deanry.my.id/dashboard');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList div').filter({ hasText: 'SMKN 8 MALANG Jl. Teluk' }).first().click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.goto('http://esbeta.deanry.my.id/dashboard');
  await page.getByRole('link', { name: ' Humas ' }).click();
  await page.getByRole('link', { name: ' Dokumen Humas' }).click();
  await page.getByRole('link', { name: ' PKL (Praktik Kerja Lapangan)' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa PKL G');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa PKL Gel 1');
  await page.getByRole('button', { name: 'Upload File * Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File * Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar siswa yang pkl ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar siswa yang pkl G');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar siswa yang pkl Gel 1 (');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar siswa yang pkl Gel 1 (B ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar siswa yang pkl Gel 1 (B dan ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar siswa yang pkl Gel 1 (B dan D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar siswa yang pkl Gel 1 (B dan D)');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen Humas', exact: true }).click();
  await page.getByRole('link', { name: ' PKL (Praktik Kerja Lapangan)' }).click();
  await page.getByRole('row', { name: '1 Daftar siswa PKL Gel 1 30-' }).locator('#dropdownMenuButton').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Lihat' }).click();
  const page1 = await page1Promise;
  await page.getByRole('row', { name: '1 Daftar siswa PKL Gel 1 30-' }).locator('#dropdownMenuButton').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Unduh' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftarsiswa ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftarsiswa PKL G');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftarsiswa PKL Gel 2');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa PKL ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa PKL G');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa PKL Gel 2');
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa PKL G');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa PKL Gel 2');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar S');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar Siswa ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar Siswa PKL G');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar Siswa PKL Gel 2');
  await page.getByRole('button', { name: 'Upload File * Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File * Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/humasindex/3');
  await page.locator('.form-group').first().click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar siswa penjemputan pkl gel 1');
  await page.getByRole('button', { name: 'Upload File * Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File * Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar siswa yang dijemput (selesai pkl)');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/humasindex/3');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('ControlOrMeta+c');
  await page.getByRole('link', { name: 'Dokumen Humas', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('eskul*()');
  await page.locator('#togglePassword').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByText('SMKN 8 MALANG Jl. Teluk').click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.goto('http://esbeta.deanry.my.id/dashboard');
  await page.getByRole('link', { name: ' Dokumen Humas' }).click();
  await page.getByRole('link', { name: ' PKL (Praktik Kerja Lapangan)' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar penjemputan siswa pkl gel 1');
  await page.getByRole('button', { name: 'Upload File * Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File * Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar penjemputan pkl');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar penjemputan pkl gel 2');
  await page.getByRole('button', { name: 'Upload File * Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File * Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar penjemputan pkl');
  await page.getByRole('button', { name: 'Atur' }).click();
  await page.getByRole('link', { name: 'Dokumen Humas', exact: true }).click();
  await page.getByRole('link', { name: ' PKL (Praktik Kerja Lapangan)' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByText('Dokumen Humas Unggah File Unggah File Nama * Tanggal File * Upload File * File').click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'TXT' }).click();
  const download1 = await download1Promise;
  
});

test('Folder', async ({ page }) => {
   await page.goto('https://esbeta.deanry.my.id/dashboard');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('heading', { name: 'SMKN 8 MALANG' }).click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.goto('http://esbeta.deanry.my.id/dashboard');
  await page.getByRole('link', { name: ' Humas ' }).click();
  await page.getByRole('link', { name: ' Dokumen Humas' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Pengumuman');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/humasfolder');
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('List Janji Temu');
  await page.locator('#editFolderForm').getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('row', { name: '1 List Janji Temu 30 Juni' }).locator('#deleteFolderForm').getByRole('button').click();
  await page.getByRole('button', { name: 'Hapus' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).fill('Mou');
  await page.getByRole('button', { name: 'Atur ulang' }).click();
});
});