import { test, expect } from '@playwright/test';

test.describe.configure({ mode: "serial" }); // Jika ingin test berurutan (opsional)
test.describe("Humas", () => {

// Gunakan state login dari guru
test.use({ storageState: 'guruState.json' });

test('Pengumuman', async ({ page }) => {
  await page.goto('https://esbeta.deanry.my.id/dashboard');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.comh');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('cked');
  await page.locator('#togglePassword').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('hacked');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('hacked');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList').getByText('Jl. Teluk Pacitan, Arjosari,').click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.getByRole('link', { name: ' Humas ' }).click();
  await page.getByRole('link', { name: ' Informasi & Konten ' }).click();
  await page.getByRole('link', { name: 'Pengumuman' }).click();
  await page.getByRole('textbox', { name: 'Judul' }).click();
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('L');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur ');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur T');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur Tahun baru ');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur Tahun baru I');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur Tahun baru Islam');
  await page.getByRole('textbox', { name: 'Keterangan' }).click();
  await page.getByRole('textbox', { name: 'Keterangan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Keterangan' }).fill('P');
  await page.getByRole('textbox', { name: 'Keterangan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Keterangan' }).fill('Pengumuman hari libur dalam rangka tahun baru slam');
  await page.getByRole('button', { name: 'Unggah' }).click();
  await page.getByRole('button', { name: 'Unggah' }).setInputFiles('muharam.jpeg');
  await page.getByLabel('This field is required.').selectOption('25');
  await page.locator('#subject-id').selectOption('131');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('L');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur ');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur T');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur Tahun ');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur Tahun B');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur Tahun Baru ');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur Tahun Baru I');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur Tahun Baru Islam');
  await page.getByRole('textbox', { name: 'Judul' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Unggah' }).click();
  await page.getByRole('button', { name: 'Unggah' }).setInputFiles('muharam.jpeg');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Keterangan' }).click();
  await page.getByRole('textbox', { name: 'Keterangan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Keterangan' }).fill('L');
  await page.getByRole('textbox', { name: 'Keterangan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Keterangan' }).fill('Liburan tahun baru hijriyah');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByLabel('This field is required.').selectOption('35');
  await page.locator('#class-section-id').click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Judul' }).click();
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('L');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Liburan ');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Liburan T');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Liburan Tahun ');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Liburan Tahun B');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Liburan Tahun Baru ');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Liburan Tahun Baru I');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Liburan Tahun Baru Islam');
  await page.getByRole('textbox', { name: 'Keterangan' }).click();
  await page.getByRole('textbox', { name: 'Keterangan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Keterangan' }).fill('L');
  await page.getByRole('textbox', { name: 'Keterangan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Keterangan' }).fill('Liburan tahu baru hijriyah');
  await page.locator('#class-section-id').selectOption('12');
  await page.locator('#subject-id').selectOption('189');
  await page.locator('#subject-id').click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Judul' }).click();
  await page.getByRole('textbox', { name: 'Judul' }).fill('L');
  await page.getByRole('textbox', { name: 'Judul' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Judul' }).fill('Libur tahun baru islam');
  await page.getByRole('textbox', { name: 'Keterangan' }).click();
  await page.getByRole('textbox', { name: 'Keterangan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Keterangan' }).fill('L');
  await page.getByRole('textbox', { name: 'Keterangan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Keterangan' }).fill('Libur tahun hijriyah');
  await page.getByRole('button', { name: 'Unggah' }).click();
  await page.getByRole('button', { name: 'Unggah' }).setInputFiles('muharam.jpeg');
  await page.getByLabel('This field is required.').selectOption('13');
  await page.locator('#subject-id').selectOption('189');
  await page.getByRole('button', { name: 'Atur' }).dblclick();
  await page.getByRole('row', { name: '1 24-06-2025 Liburan Tahun' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.locator('#title').click();
  await page.locator('#description').click();
  await page.locator('#description').press('ArrowLeft');
  await page.locator('#description').press('ArrowLeft');
  await page.locator('#description').press('ArrowLeft');
  await page.locator('#description').press('ArrowLeft');
  await page.locator('#description').press('ArrowLeft');
  await page.locator('#description').press('ArrowLeft');
  await page.locator('#description').fill('Liburan tahun baru hijriyah');
  await page.locator('#formdata').getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('row', { name: '3 24-06-2025 Libur Tahun baru' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.getByRole('button', { name: 'Batal' }).click();
  await page.getByRole('row', { name: '10 07-05-2025 UH MULOK PJOK' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Hapus' }).click();
  await page.getByRole('button', { name: 'Ya, hapus' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('span').filter({ hasText: 'Keterangan' }).click();
  await page.locator('.fixed-table-toolbar').click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Keterangan' }).nth(1).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'TXT' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: '10' }).click();
  await page.getByRole('link', { name: '5' }).click();
  await page.getByRole('link', { name: 'next page' }).click();
  await page.getByRole('link', { name: 'previous page' }).click();
  await page.getByRole('link', { name: 'to page 2' }).click();
});
});