import { test, expect } from '@playwright/test';

test.describe.configure({ mode: "serial" }); // Jika ingin test berurutan (opsional)
test.describe("Tes mata pelajaran - tambah bab", () => {

// Gunakan sesi login guru yang sudah disimpan
test.use({ storageState: 'guruState.json' });

test('test', async ({ page }) => {
  await page.goto('https://esbeta.deanry.my.id/dashboard');
  await page.getByRole('link', { name: ' Kurikulum ' }).click();
  await page.getByRole('link', { name: ' Tugas Siswa ' }).click();
  await page.getByRole('link', { name: 'Buat Tugas' }).click();
  await page.getByRole('button', { name: 'Tambah Penugasan' }).click();
  await page.getByLabel('Kelas *').selectOption('35');
  await page.locator('#subject-id').selectOption('141');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Merangkum');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah materi terkait sejara atletik, cabor apa saja yang termasuk atletik, dan jelaskan masing-masing pinnya');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('lari.jpg');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).fill('2025-06-04T00:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-30T08:00');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-06T00:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('');
  await page.getByRole('spinbutton', { name: 'Poin *' }).press('CapsLock');
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('75');
  await page.locator('#max_file').selectOption('50');
  await page.locator('#create-form i').click();
  await page.getByRole('textbox', { name: 'Hari Tambahan untuk' }).fill('3');
  await page.getByRole('button', { name: 'docx' }).click();
  await page.getByRole('button', { name: 'pdf' }).click();
  await page.getByRole('button', { name: 'jpeg' }).click();
  await page.getByRole('button', { name: 'jpg' }).click();
  await page.getByRole('button', { name: 'png' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Tambah Penugasan' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByLabel('Kelas *').selectOption('20');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('#subject-id').selectOption('99');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Tugas * This field is' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas * This field is' }).fill('T');
  await page.getByRole('textbox', { name: 'Nama Tugas * This field is' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Praktek ');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Praktek L');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Praktek Lari ');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Praktek Lari E');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Praktek Lari Estafet');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).click();
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('T');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Tugas ini dilakukan secara berkelompok, masinng-masing kelompok terdiri dari 4 orang. praktekan dan buat video upload youtube linknya kumpulkan');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('lari.jpg');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).fill('2025-06-03T00:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-29T08:00');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ControlOrMeta+Z');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Tugas ini dilakukan secara berkelompok, masinng-masing kelompok terdiri dari 4 orang. bu');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ControlOrMeta+Y');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ControlOrMeta+Y');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ControlOrMeta+Y');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-29T08:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-05T00:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('100');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('75');
  await page.locator('#max_file').selectOption('20');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('checkbox', { name: 'Pengiriman Ulang Diizinkan ' }).check();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('checkbox', { name: 'Pengiriman Ulang Diizinkan ' }).uncheck();
  await page.locator('#create-form i').click();
  await page.getByRole('textbox', { name: 'Hari Tambahan untuk' }).fill('3');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Tambah Penugasan' }).click();
  await page.getByLabel('Kelas *').selectOption('20');
  await page.locator('#subject-id').selectOption('99');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).click();
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('T');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas praktek lari estafet');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).click();
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('B');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Bentuklah kelompok yang terdiri dari 4 orang, praktekan lari estafet, reka dan upload youtube, linknya kumpulkan');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).fill('2025-05-02T00:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).fill('2025-06-02T00:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-28T08:00');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-06T00:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('75');
  await page.locator('#max_file').selectOption('50');
  await page.locator('#create-form i').click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Tambah Penugasan' }).click();
  await page.getByLabel('Kelas *').selectOption('31');
  await page.locator('#subject-id').selectOption('181');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).click();
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('T');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas merangkum bab atletik');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).click();
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('R');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah materi atletik dan cabor apa saja yang termasuk atletik jelaskan masing-masing poinnya');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('Passing bawah, passing atas, & smash pada Permainan Bola Voli - Razaf Zulfikry.mp3');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).fill('2024-06-04T00:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-30T08:00');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-06T12:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('75');
  await page.locator('#max_file').selectOption('50');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-06T00:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-06-30T08:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-30T08:00');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).fill('2024-06-05T00:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('lari.jpg');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-03T00:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-06T00:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-06-30T08:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-30T08:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('75');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Atur ulang' }).click();
  await page.getByLabel('Kelas *').selectOption('31');
  await page.locator('#subject-id').selectOption('181');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).click();
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('T');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas ');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas M');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Merangkum');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas MerangkumR');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Merangkum');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).click();
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('R');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah bab atletik dan cabangnya apa aja jelaskan tiap poin-poinnya');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).fill('2025-06-05T00:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-06-06T08:00');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-08T00:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('5');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-28T08:00');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('75');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-03T00:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-08T00:00');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).fill('2025-05-30T00:00');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Tambah Penugasan' }).click();
  await page.getByLabel('Kelas *').selectOption('34');
  await page.locator('#subject-id').selectOption('141');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).click();
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('T');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas ');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas M');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Merangkum');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).click();
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('R');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah bab atletik dan cabangnya, jelaskan tiap poinnya');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).fill('2025-06-08T12:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-28T08:00');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-08T00:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('75');
  await page.locator('#max_file').selectOption('10');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).fill('2025-06-05T12:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('75');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Tambah Penugasan' }).click();
  await page.getByLabel('Kelas *').selectOption('25');
  await page.locator('#subject-id').selectOption('131');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).click();
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('T');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas ');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Merangkum');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).click();
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('R');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah materi atletik dan cabangny ');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah materi atletik dan cabangnya apa aja. ');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah materi atletik dan cabangnya apa aja. J ');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah materi atletik dan cabangnya apa aja. Jelaskan tiap poinnya ');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tenggat Waktu * This field is' }).fill('52025-06-01T00:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-25T08:00');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-05T00:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('80');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('85');
  await page.locator('#max_file').selectOption('10');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://esbeta.deanry.my.id/assignment');
  await page.getByRole('button', { name: 'Tambah Penugasan' }).click();
  await page.getByLabel('Kelas *').selectOption('25');
  await page.locator('#subject-id').selectOption('131');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).click();
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('T');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas ');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Merangkum');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas MerangkumR');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Tugas *' }).fill('Tugas Merangkum');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).click();
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('R');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah bab atletik dan jelaskan cangnya apa aja');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Instruksi Penugasan' }).fill('Rangkumlah bab atletik dan jelaskan cabangnya apa aja');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).click();
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tenggat Waktu *' }).fill('2025-06-01T10:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).click();
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).fill('2025-05-30T08:00');
  await page.getByRole('textbox', { name: 'Tgl Mulai *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).click();
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tgl Selesai' }).fill('2025-06-05T00:00');
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('80');
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).click();
  await page.getByRole('spinbutton', { name: 'Nilai Kelulusan *' }).fill('85');
  await page.locator('#max_file').selectOption('10');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).click();
  await page.getByRole('spinbutton', { name: 'Poin *' }).press('ControlOrMeta+A');
  await page.getByRole('spinbutton', { name: 'Poin *' }).fill('100');
  await page.getByRole('button', { name: 'docx' }).click();
  await page.getByRole('button', { name: 'jpeg' }).click();
  await page.getByRole('button', { name: 'jpg' }).click();
  await page.getByRole('button', { name: 'pdf' }).click();
  await page.getByRole('button', { name: 'png' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('row', { name: '3 Tugas Merangkum XII METRO B' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.getByRole('spinbutton', { name: 'Poin' }).click();
  await page.getByRole('spinbutton', { name: 'Poin' }).fill('100');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'to page 2' }).click();
  await page.getByRole('row', { name: '4 Tugas mengirim file XII TKJ' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Hapus' }).click();
  await page.getByRole('button', { name: 'Yes, delete it' }).click();
  await page.getByRole('link', { name: 'to page 1' }).click();
  await page.getByRole('row', { name: '3 Tugas Merangkum XII METRO B' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Detail' }).click();
  await page.getByRole('button', { name: ' Edit' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('row', { name: '3 Tugas Merangkum XII METRO B' }).locator('#dropdownMenuButton').click();
  await page.getByRole('link', { name: 'Detail' }).click();
  await page.getByRole('button', { name: 'Tutup' }).click();
  await page.locator('#filter-class-section-id').selectOption('35');
  await page.locator('#filter-class-section-id').selectOption('');
  await page.getByLabel('Tahun Ajaran').selectOption('3');
  await page.getByLabel('Tahun Ajaran').selectOption('1');
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('estafet');
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Hide/Show pagination' }).click();
  await page.getByRole('button', { name: 'Hide/Show pagination' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label:nth-child(5)').click();
  await page.locator('.fixed-table-toolbar').click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.goto('https://esbeta.deanry.my.id/assignment');
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label:nth-child(5)').click();
  await page.locator('#toolbar div').first().click();
  await page.getByRole('button', { name: 'Export' }).click();
  await page.getByRole('button', { name: 'Export' }).press('AudioVolumeMute');
  await page.getByRole('button', { name: 'Export' }).press('AudioVolumeMute');
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label:nth-child(5)').click();
  await page.getByRole('button', { name: 'Export' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'CSV' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: '5' }).click();
  await page.getByRole('link', { name: '10' }).click();
  await page.getByRole('button', { name: '10' }).click();
  await page.getByRole('link', { name: '20' }).click();
  await page.getByRole('button', { name: '20' }).click();
  await page.getByRole('link', { name: '50' }).click();
  await page.getByRole('button', { name: '50' }).click();
  await page.getByRole('link', { name: '5', exact: true }).click();
  await page.getByRole('link', { name: 'to page 3' }).click();
  await page.getByRole('link', { name: 'previous page' }).click();
  await page.getByRole('link', { name: 'next page' }).click();
  await page.getByRole('link', { name: 'next page' }).click();
});
});