import { test, expect } from '@playwright/test';
test.describe.configure({ mode: 'serial' }); 
test.describe('CRUDS Topik', () => {
test('test', async ({ page }) => {
  await page.goto('https://esbeta.deanry.my.id/lesson-topic');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('081230093978');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'School Code' }).click();
  await page.getByRole('textbox', { name: 'School Code' }).fill('CH');
  await page.getByRole('textbox', { name: 'School Code' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'School Code' }).fill('CH20248');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('081230093978');
  await page.getByRole('textbox', { name: 'School Code' }).click();
  await page.getByRole('textbox', { name: 'School Code' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'School Code' }).fill('SCH');
  await page.getByRole('textbox', { name: 'School Code' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'School Code' }).fill('SCH20248');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('link', { name: ' Mata Pelajaran ' }).click();
  await page.getByRole('link', { name: 'Tambah Topik' }).click();
  await page.locator('#class-section-id').selectOption('35');
  await page.locator('#subject-id').selectOption('141');
  await page.locator('#topic-lesson-id').selectOption('22');
  await page.getByRole('textbox', { name: 'Nama Topik' }).click();
  await page.getByRole('textbox', { name: 'Nama Topik' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Topik' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama Topik' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Topik' }).fill('Passing');
  await page.getByRole('textbox', { name: 'Deskripsi Topik' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Topik' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Topik' }).fill('C');
  await page.getByRole('textbox', { name: 'Deskripsi Topik' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Topik' }).fill('Cara passing dan macamnya');
  await page.getByRole('button', { name: ' Tambah File' }).click();
  await page.locator('#file_type').selectOption('file_upload');
  await page.getByRole('textbox', { name: 'Nama File' }).click();
  await page.getByRole('textbox', { name: 'Nama File' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama File' }).fill('P');
  await page.getByRole('textbox', { name: 'Nama File' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama File' }).fill('Passing');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('passing.jpeg');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('row', { name: '1 Passing Baca selengkapnya' }).getByRole('link').nth(1).click();
  await page.getByRole('textbox', { name: 'Nama Pelajaran' }).click();
  await page.getByRole('textbox', { name: 'Nama Pelajaran' }).fill('Passing ');
  await page.getByRole('textbox', { name: 'Nama Pelajaran' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Pelajaran' }).fill('Passing A');
  await page.getByRole('textbox', { name: 'Nama Pelajaran' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Pelajaran' }).fill('Passing Atas');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).fill('T');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).fill('Tutorial passing atas dalam permainana bola');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).fill('Tutorial passing atas dalam permainan bola');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Deskripsi Pelajaran' }).fill('Tutorial passing atas dalam permainan bola voli');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Pratinjau Berkas' }).click();
  const page1 = await page1Promise;
  await page1.locator('body').click();
  await page.getByRole('textbox', { name: 'Nama File' }).click();
  await page.getByRole('textbox', { name: 'Nama File' }).fill('Passing ');
  await page.getByRole('textbox', { name: 'Nama File' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama File' }).fill('Passing A');
  await page.getByRole('textbox', { name: 'Nama File' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama File' }).fill('Passing Atas');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('passing atas.jpeg');
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Pratinjau Berkas' }).click();
  const page2 = await page2Promise;
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('row', { name: '5 oke Baca selengkapnya oke' }).getByRole('link').nth(2).click();
  await page.getByRole('button', { name: 'Ya, hapus' }).click();
  await page.getByLabel('Bagian Kelas').selectOption('12');
  await page.getByLabel('Bagian Kelas').selectOption('35');
  await page.locator('#filter-subject-id').selectOption('141');
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('V');
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('Voli');
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('span').filter({ hasText: 'Keterangan' }).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'TXT' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'to page 2' }).click();
  await page.getByRole('button', { name: '10' }).click();
  await page.getByRole('link', { name: '5' }).click();
});
});