import { test, expect } from '@playwright/test';

test.describe.configure({ mode: "serial" }); // Jika ingin test berurutan (opsional)
test.describe("Tes Dokumen Kesiswaan", () => {

// Gunakan state login dari guru
test.use({ storageState: 'guruState.json' });

test('test dokumen kesiswaan', async ({ page }) => {
  await page.goto('https://esbeta.deanry.my.id/dashboard');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.comh');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('hacked');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('hacked');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('div:nth-child(2) > .school-info > .selected-check').click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.goto('http://esbeta.deanry.my.id/dashboard');
  await page.getByRole('link', { name: ' Kesiswaan ' }).click();
  await page.getByRole('link', { name: ' Dokumen Kesiswaan' }).click();
  await page.getByRole('link', { name: ' Form Absen Siswa' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar Absensi Pra-Magang');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Data absensi kehadiran siswa di kegiatan pra magang');
  await page.getByRole('button', { name: 'Upload File * Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File * Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/kesiswaanindex/10');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/kesiswaanindex/10');
  await page.getByRole('link', { name: ' Absensi ' }).click();
  await page.getByRole('link', { name: 'Laporan Absensi', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('hacked');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList').getByText('Jl. Teluk Pacitan, Arjosari,').click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.goto('http://esbeta.deanry.my.id/dashboard');
  await page.getByRole('link', { name: ' Absensi ' }).click();
  await page.getByRole('link', { name: 'Laporan Absensi', exact: true }).click();
  await page.getByRole('link', { name: ' Kesiswaan ' }).click();
  await page.getByRole('link', { name: ' Dokumen Kesiswaan' }).click();
  await page.locator('.course-card > .card-body').first().click();
  await page.getByRole('link', { name: ' Form Absen Siswa' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar absensi pas foto ijazah ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar absensi pas foto ijazah XII');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('L');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('L');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('List ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('List K');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('List Kehadiran siswa pas foto ijazah');
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar K');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar Kehadiran siswa pas foto ijazah');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('ControlOrMeta+c');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar Kehadiran siswa pas foto ijazah');
  await page.getByRole('button', { name: 'Upload File * Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File * Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar kehadiran ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar kehadiran BKK ');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama * Nama' }).fill('Daftar kehadiran BKK 2025');
  await page.getByRole('button', { name: 'Upload File * Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File * Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('D');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Daftar hadir bkk 2025');
  await page.getByRole('button', { name: 'Atur' }).click();
  await page.getByRole('link', { name: ' Dokumen Kesiswaan' }).click();
  await page.getByRole('link', { name: ' Form Absen Siswa' }).click();
  await page.getByRole('row', { name: '4 Rekap kehadiran Classmeet' }).locator('#dropdownMenuButton').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Lihat' }).click();
  const page1 = await page1Promise;
  await page.getByRole('row', { name: '4 Rekap kehadiran Classmeet' }).locator('#dropdownMenuButton').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Unduh' }).click();
  const download = await downloadPromise;
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Search' }).fill('');
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByRole('cell', { name: 'Agung Cahyono, S.Pd., Gr' }).first().click();
  await page.getByRole('button', { name: 'Columns' }).click();
  await page.locator('label').filter({ hasText: 'Deskripsi' }).nth(1).click();
  await page.getByRole('checkbox', { name: 'Deskripsi' }).press('AudioVolumeDown');
  await page.locator('#table_list').getByText('Deskripsi').click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Export' }).click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'XML' }).click();
  const download1 = await download1Promise;
  await page.getByRole('button', { name: '10' }).click();
  await page.getByRole('link', { name: '20' }).click();
  await page.getByRole('button', { name: '20' }).click();
  await page.getByRole('link', { name: '5' }).click();
  await page.getByRole('link', { name: 'next page' }).click();
  await page.getByRole('link', { name: 'to page 3' }).click();
  await page.getByRole('link', { name: 'previous page' }).click();
});
});