import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://esbeta.deanry.my.id/dashboard');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533');
  await page.getByRole('textbox', { name: 'Email' }).press('AudioVolumeDown');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn9*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('smkn8*()');
  await page.locator('#togglePasswordShowHide span').click();
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList div').filter({ hasText: 'SMKN 8 MALANG Jl. Teluk' }).first().click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.getByRole('link', { name: ' Humas ' }).click();
  await page.getByRole('link', { name: ' Sarpras ' }).click();
  await page.getByRole('link', { name: ' Dokumen Sarpras' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Surat ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Surat P');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Surat Peminjaman');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).click();
  await page.getByRole('textbox', { name: 'Nama Folder' }).fill('Surat Peminjaman organisasi');
  await page.locator('#editFolderForm').getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('row', { name: '1 Surat Peminjaman organisasi' }).locator('#deleteFolderForm').getByRole('button').click();
  await page.getByRole('button', { name: 'Hapus' }).click();
  await page.getByRole('link', { name: 'Kelola Folder' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama This field is required.' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama This field is required.' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama This field is required.' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).press('ControlOrMeta+r');
  await page.getByRole('textbox', { name: 'Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Surat ');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Surat P');
  await page.getByRole('textbox', { name: 'Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama' }).fill('Surat Peminjaman');
  await page.getByRole('button', { name: 'Atur ulang' }).click();
  await page.getByRole('link', { name: 'Dokumen Sarpras' }).click();
  await page.getByRole('link', { name: ' Sarpas' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat peminjaman barang ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat peminjaman barang OSIS');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('Log-Book Magang_Zara Salsa Aulia.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('s');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('S');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Surat peminjaman untuk acara ');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Surat peminjaman untuk acara MPLS');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/sarpasindex/2');
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Peminjaman ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Peminjaman B');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Peminjaman Barang ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Peminjaman Barang OSIS');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('S');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Surat peminjman untuk acara mpls');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('link', { name: 'Dokumen Sarpras', exact: true }).click();
  await page.getByRole('link', { name: ' Sarpas' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat P');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Peminjaman ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Peminjaman B');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Peminjaman Barang ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Peminjaman Barang BDI');
  await page.getByRole('textbox', { name: 'Tanggal File * Tanggal File *' }).fill('');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat peminjaman barang ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat peminjaman barang BDI');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ControlOrMeta+A');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ControlOrMeta+C');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('ControlOrMeta+V');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat I');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Izin acara diklat ');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat Izin acara diklat PA');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('S');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Surat izin acara diklat pecinta alam');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/sarpasindex/2');
  await page.getByRole('link', { name: 'Dokumen Sarpras' }).click();
  await page.getByRole('link', { name: 'Dokumen Sarpras', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.coms');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('kn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email' }).fill('agungcahyono533@gmail.com');
  await page.getByRole('textbox', { name: 'Password Password harus diisi' }).click();
  await page.getByRole('textbox', { name: 'Password Password harus diisi' }).fill('smkn8*()');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.locator('#schoolsList i').nth(1).click();
  await page.getByRole('button', { name: 'Lanjutkan ke Dashboard' }).click();
  await page.getByRole('link', { name: ' Dokumen Sarpras' }).click();
  await page.goto('https://esbeta.deanry.my.id/folder/sarpasfolder');
  await page.getByRole('link', { name: ' Sarpas' }).click();
  await page.goto('http://esbeta.deanry.my.id/folder/sarpasindex/2');
  await page.getByRole('textbox', { name: 'Nama Nama' }).click();
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('S');
  await page.getByRole('textbox', { name: 'Nama Nama' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama Nama' }).fill('Surat peminjaman barang tari');
  await page.getByRole('button', { name: 'Upload File Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File Upload File' }).setInputFiles('rekap_absensi.pdf');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).click();
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('S');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Deskripsi Deskripsi' }).fill('Surat peminjaman ekskul tari');
  await page.getByRole('button', { name: 'Simpan' }).click();
});